import type { Station } from './api';

// Authoritative station list for the UI (station → id).
// We still try to load stations from backend, but in the UI we prefer these IDs
// to keep them stable and consistent with your dataset.
export const STATIC_STATIONS: Station[] = [
  {
    id: '510051',
    title: 'Kraków Główny',
    city: 'Kraków',
    region: 'Małopolska',
    country: 'Poland',
    address: 'Ul. Pawia 5a, 31-154',
    coordinates: '50.0675, 19.9461',
    international_codes: '',
  },
  {
    id: '510042',
    title: 'Katowice',
    city: 'Katowice',
    region: 'Upper Silesia',
    country: 'Poland',
    address: 'Plac Marii i Lecha Kaczyńskich 2, 40-000',
    coordinates: '50.2592, 19.0219',
    international_codes: '',
  },
  {
    id: '510573',
    title: 'Mysłowice',
    city: 'Mysłowice',
    region: 'Upper Silesia',
    country: 'Poland',
    address: 'Powstańców 128, 41-400',
    coordinates: '50.2379, 19.1419',
    international_codes: '',
  },
  {
    id: '510146',
    title: 'Zabrze',
    city: 'Zabrze',
    region: 'Upper Silesia',
    country: 'Poland',
    address: 'Plac Dworcowy 2, 41-800',
    coordinates: '50.3070, 18.7862',
    international_codes: '',
  },
  {
    id: '510024',
    title: 'Gliwice',
    city: 'Gliwice',
    region: 'Upper Silesia',
    country: 'Poland',
    address: 'Bohaterów Getta Warszawskiego 12, 44-100',
    coordinates: '50.3013, 18.6777',
    international_codes: '',
  },
  {
    id: '510085',
    title: 'Opole Główne',
    city: 'Opole',
    region: 'Opole',
    country: 'Poland',
    address: 'Krakowska 48, 46-020',
    coordinates: '50.6673, 17.9263',
    international_codes: '',
  },
  {
    id: '510062',
    title: 'Leszno',
    city: 'Leszno',
    region: 'Wielkopolska',
    country: 'Poland',
    address: 'Dworcowa 1, 64-100',
    coordinates: '51.8448, 16.5744',
    international_codes: '',
  },
  {
    id: '510177',
    title: 'Poznań Główny',
    city: 'Poznań',
    region: 'Wielkopolska',
    country: 'Poland',
    address: 'Dworcowa 2, 61-801',
    coordinates: '52.4014, 16.9175',
    international_codes: '',
  },
  {
    id: '510091',
    title: 'Piła Główna',
    city: 'Piła',
    region: 'Wielkopolska',
    country: 'Poland',
    address: 'Zygmunta Starego 1, 64-920',
    coordinates: '53.1433, 16.7425',
    international_codes: '',
  },
  {
    id: '510048',
    title: 'Kołobrzeg',
    city: 'Kołobrzeg',
    region: 'West Pomerania',
    country: 'Poland',
    address: 'Al. Kolejowa 3, 78-100',
    coordinates: '54.1807, 15.5750',
    international_codes: '',
  },
  {
    id: '510143',
    title: 'Wrocław Główny',
    city: 'Wrocław',
    region: 'Lower Silesia',
    country: 'Poland',
    address: 'Marszałka Józefa Piłsudskiego 105, 50-085',
    coordinates: '51.0987, 17.0379',
    international_codes: '',
  },
  {
    id: '510363',
    title: 'Jaworzno Szczakowa',
    city: 'Jaworzno',
    region: 'Upper Silesia',
    country: 'Poland',
    address: 'Kolejarzy, 43-602',
    coordinates: '50.2471, 19.2934',
    international_codes: '',
  },
];

